### ISSUE TITLE
Exposing public member variables of c++ classes with clbind

### ISSUE THREAD

**Issue by HeyFlash** [drmeister/clasp#136] opened 2015-09-25 18:40 UTC
Currently, exposing via def_readonly, etc. does not work.
An example can be found with the type member of the sf::Event class in https://github.com/HeyFlash/SFML/blob/master/src/SFML/Window/ClaspBindingWindow.cpp 

(Usage: https://github.com/HeyFlash/clasp-stuff/blob/master/sfml-test.lsp -- replace sf:get-type with sf:type and it no longer works)

**Comment by Shinmera** [comment] 2015-09-25 19:27
Is this a regression, or something that was always broken?

**Comment by HeyFlash** [comment] 2015-09-25 20:30
Broken is probably the wrong word, it is a feature that was never supported.
drmeister activated the def_readonly not too long ago, but it never worked. 
So it was promoted directly from nonexisting feature to bug. ;-)

**Comment by Shinmera** [comment] 2015-09-25 20:31
Right, should hopefully be in for 0.4.0

**Comment by Shinmera** [comment] 2015-10-28 23:20
Since this now seems to be fixed, if you could provide me with a (if possible minimal) way to reproduce this, that'd be great.

**Comment by drmeister** [comment] 2015-10-30 13:46
That's tough because it's a C++ API feature.  We would have to add an example to the https://github.com/drmeister/demo-clasp-cxx  demo.
Flash-'s SFML library will be using this more and more.

**Comment by Shinmera** [comment] 2015-11-10 20:35
Can confirm properly fixed on 712260b4038b40e04d8928b7183e2af5da416a0d, also see #158.

**Closed by Shinmera** 2015-11-10 20:35 UTC
Labels: bug, clbind
