### ISSUE TITLE
Segmentation fault when quickloading system "babel" 

### ISSUE THREAD

**Issue by dg1sbg** [drmeister/clasp#315] opened 2016-11-06 23:14 UTC
```
Starting Boehm cclasp 2acce2c ... loading image... it takes a few seconds
Top level.
> (load "~/clasp-load-cffi")
To load "babel":
  Load 1 ASDF system:
    babel
; Loading "babel"
84455 Segmentation fault: 11
```
See also:
[clasp-load-cffi.lisp](https://github.com/drmeister/clasp/files/574195/clasp-load-cffi.lisp.txt)

For reproducing this, please do:
1. Load trivial-features (requires my clasp-enabled version from https://github.com/dg1sbg/trivial-features/tree/dev-clasp !)
2. Load BABEL: (ql:quickload "babel")

**Comment by dg1sbg** [comment] 2016-11-06 23:32
Additional info: Running in lldb by 
 lldb -- ./iclasp-boehm -i cclasp-boehm-image.fasl
=>
Current executable set to './iclasp-boehm' (x86_64).
(lldb) settings set -- target.run-args  "-i" "cclasp-boehm-image.fasl"
run
=>
Starting Boehm cclasp 2acce2c ... loading image... it takes a few seconds
> (pushnew #p "~/swdev/trivial-features/src/trivial-features/" asdf:*central-registry*)

(#P"/Users/frgo/swdev/trivial-features/src/trivial-features/"
 #P"/opt/common-lisp/quicklisp/quicklisp/")
> (asdf:load-system :trivial-features)

reveals:

Process 86911 stopped
* thread #1: tid = 0x356688, 0x00000001023643fa iclasp-boehm`llvmo::llvm_sys__cxxDataStructuresInfo() [inlined] gctools::smart_ptr<core::Cons_O> gctools::ConsAllocator<core::Cons_O>::allocate<gctools::smart_ptr<core::T_O>&, gctools::smart_ptr<core::T_O>&>(gctools::smart_ptr<core::T_O>&&&, gctools::smart_ptr<core::T_O>&&&) + 17 at gcalloc.h:284, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=2, address=0x7fff5ebffdd8)
    frame #0: 0x00000001023643fa iclasp-boehm`llvmo::llvm_sys__cxxDataStructuresInfo() [inlined] gctools::smart_ptr<core::Cons_O> gctools::ConsAllocator<core::Cons_O>::allocate<gctools::smart_ptr<core::T_O>&, gctools::smart_ptr<core::T_O>&>(gctools::smart_ptr<core::T_O>&&&, gctools::smart_ptr<core::T_O>&&&) + 17 at gcalloc.h:284 [opt]
   281 	    static smart_ptr<Cons> allocate(ARGS &&... args) {
   282 	#ifdef USE_BOEHM
   283 	      monitor_allocation(kind_cons,sizeof(Cons));
-> 284 	      Cons* cons = reinterpret_cast<Cons*>(GC_MALLOC(sizeof(Cons)));
   285 	      new (cons) Cons(std::forward<ARGS>(args)...);
   286 	      POLL_SIGNALS();
   287 	      return smart_ptr<Cons>((Tagged)tag_cons(cons));

**Comment by drmeister** [comment] 2016-11-22 22:22
I think this was due to running out of stack when clasp was trying to serialize very long lists to fasl files as recursive CONS cells.   I added a function to serialize lists.  This should fix 99% of cases.

**Comment by dg1sbg** [comment] 2016-12-04 19:47
This issue may be closed. Fixed in now available commit.

**Comment by Shinmera** [comment] 2016-12-05 11:15
I can't close this until I can confirm it, which won't be until the next Quicklisp release rolls out.

**Comment by drmeister** [comment] 2016-12-14 05:19
I tried (ql:quickload "babel") but it failed because I hadn't installed trival-features.
dg1sbg - could you briefly describe how to install it from the url you provided?
Is there anything more than to clone the repo and run something within lisp.

**Comment by Shinmera** [comment] 2016-12-14 08:18
Clone trivial-features to the local-projects folder within the Quicklisp directory.

**Comment by Bike** [comment] 2017-07-12 01:31
loading babel no longer segfaults

**Closed by Bike** 2017-07-12 01:31 UTC
Labels: bug
