### ISSUE TITLE
displaced array breaks for element-type character

### ISSUE THREAD

**Issue by dkochmanski** [drmeister/clasp#276] opened 2016-09-01 04:56 UTC
commit: ffc61118f7e9bafd339a2442f00c6bd2b38e4606
test case:
```common-lisp
> (make-array 3
                    :element-type 'character
                    :displaced-to (make-array 5
                                              :element-type 'character
                                              :initial-contents "abcde")
                    :displaced-index-offset 1)

Condition of type: SIMPLE-ERROR
Cannot displace the array, because the element types don't match

Available restarts:
(use :r1 to invoke restart 1)

1. (RESTART-TOPLEVEL) Go back to Top-Level REPL.

Broken at frame[102] CALL-WITH-VARIABLE-BOUND.
 File: #P"/data/Warsztat/Repozytoria/clasp/src/core/compiler.cc" (Position #37160)
```

**Comment by dkochmanski** [comment] 2016-09-01 05:23
```common-lisp
> (make-array 5
                               :element-type 'character
                               :initial-contents "abcde")

"abcde"
> (type-of *)

(SIMPLE-ARRAY BASE-CHAR (1 5))

> (subtypep 'base-char 'character)
T
T
```

**Comment by Shinmera** [comment] 2016-09-01 05:33
Dupe of #179

**Closed by Shinmera** 2016-09-01 05:33 UTC
Labels: duplicate
