### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by Immortalin** [drmeister/clasp#262] opened 2016-07-22 10:02 UTC
Considering the long build times, do you think you can set up a build server and provide binary releases? You can integrate this with [Roswell](https://github.com/roswell/roswell) for easier end user installation.

**Comment by Shinmera** [comment] 2016-07-22 11:43
There is already a CI system based on [Autobuild](https://github.com/Shinmera/autobuild) active. However, it doesn't do packaging of binary releases yet, in part because doing so correctly would require extensions to Autobuild itself, but also a significant effort on our part to determine what libraries we have to ship with it and how in order for it to work on other distributions.
The CI results are also currently only shared privately as I don't want to expose the build machines to the internet quite yet before making sure that Autobuild has proper security measures to prevent abuse.

**Comment by snmsts** [comment] 2016-07-22 19:29
How about attach files on github release? It would be safe.
I'm appreciate if I could release Roswell with partial support installing clasp-bin.

**Comment by Shinmera** [comment] 2016-07-22 21:36
Sure, but that doesn't solve the problem of resolving foreign library dependencies and making sure the shipped package actually works on more distributions than one.

**Comment by snmsts** [comment] 2016-07-23 06:31
worse is better than nothing.

**Comment by Shinmera** [comment] 2016-07-23 06:34
I disagree on that. Putting up any kind of release would only prompt people to report problems with it not working on "x distribution of my choice". I'd rather the issue is investigated thoroughly first than throwing something out just to have it out.

**Comment by snmsts** [comment] 2016-07-23 08:26
sure...

**Comment by Immortalin** [comment] 2016-07-24 00:33
At least add support for the most important ones I.e. Ubuntu, OS X and Windows

**Comment by Shinmera** [comment] 2016-07-24 06:03
Everyone who's contributing to this project is dealing with other, more pressing issues at the moment, or simply doesn't have the time to deal with this. If you'd like to take up the time and work to provide this, then you'd be more than welcome to. I'm not "dragging my feet" because I'm not actively stopping anyone.

**Comment by drmeister** [comment] 2016-08-09 05:21
If someone would like to help with this it would be very welcome.  I don't have the resources at the moment to implement continuous integration and generation of binaries.  I would LOVE to have this setup though.

**Comment by Immortalin** [comment] 2016-08-09 05:56
@drmeister I am currently working on getting it to build on Travis(see my fork) but I running into quite a few dependencies issues(to be specific, the problem of which git modules to use and clasp-external. I would also remmend having a github mirror of common-lisp.net's git repo)

**Comment by Shinmera** [comment] 2016-08-09 06:07
I don't think Travis will work due to the 2GB RAM limit on their insstances.

**Comment by pipping** [comment] 2016-09-09 13:54
@Immortalin Maybe you find https://github.com/pipping/docker-clasp to be a step in the right direction.

**Comment by Shinmera** [comment] 2016-10-13 14:42
I'll close this for the time being until Clasp is able to accommodate for more restricted build environments such as what Travis & co. require.

**Closed by Shinmera** 2016-10-13 14:42 UTC
Labels: question
