### ISSUE TITLE
compile: can't compile an ordinary function from toplevel

### ISSUE THREAD

**Issue by dkochmanski** [drmeister/clasp#285] opened 2016-09-01 08:05 UTC
```
(defun meaningless-user-function-for-universe (x y z)
  (list (+ x 1) (+ y 2) (+ z 3)))

MEANINGLESS-USER-FUNCTION-FOR-UNIVERSE
> (compile 'meaningless-user-function-for-universe)

Condition of type: SIMPLE-ERROR
Could not compile func

Available restarts:
(use :r1 to invoke restart 1)

1. (RESTART-TOPLEVEL) Go back to Top-Level REPL.

Broken at frame[104] CALL-WITH-VARIABLE-BOUND.
 File: #P"/data/Warsztat/Repozytoria/clasp/src/core/compiler.cc" (Position #37160)
```

**Comment by Shinmera** [comment] 2016-09-01 08:06
Dupe of #145

**Closed by Shinmera** 2016-09-01 08:06 UTC
Labels: bug, duplicate
