### ISSUE TITLE
Symbol with empty name

### ISSUE THREAD

**Issue by dkochmanski** [drmeister/clasp#277] opened 2016-09-01 05:38 UTC
commit ffc61118f7e9bafd339a2442f00c6bd2b38e4606
test case:
```
> ':||

Condition of type: SIMPLE-PROGRAM-ERROR
Could not interpret symbol state(tsymk) at 0 symbol: [:]

Available restarts:
(use :r1 to invoke restart 1)

1. (RESTART-TOPLEVEL) Go back to Top-Level REPL.

Broken at frame[100] CALL-WITH-VARIABLE-BOUND.
 File: #P"/data/Warsztat/Repozytoria/clasp/src/core/compiler.cc" (Position #37160)
```

**Comment by Shinmera** [comment] 2016-09-01 07:25
Dupe of #62

**Closed by Shinmera** 2016-09-01 07:25 UTC
Labels: bug, duplicate
