### ISSUE TITLE
Remove useless files

### ISSUE THREAD

**Issue by drmeister** [drmeister/clasp#173] opened 2015-11-21 12:41 UTC
There's nothing like inviting the neighbors over and have them comment on the untidiness of ones home to motivate one to clean house.

**Comment by Shinmera** [comment] 2015-11-21 12:43
How is this different from #45 and #41? What exactly should be cleaned up?
Please specify so that this can be confirmed and closed at a distinguishable point in time.

**Comment by drmeister** [comment] 2015-11-26 14:46
#41 and #45 are equivalent to this.   #88 is a separate issue

**Comment by Shinmera** [comment] 2015-11-26 14:52
Dupe of #41

**Closed by Shinmera** 2015-11-26 14:52 UTC
Labels: cleanup, duplicate
