### ISSUE TITLE
'config-cache.jam' still missing

### ISSUE THREAD

**Issue by chriskmanx** [drmeister/clasp#79] opened 2015-01-22 21:31 UTC
This is a recurrence of https://github.com/drmeister/clasp/issues/23 on OSX.

With BOOST_BUILD_PATH properly set and pointing to the externals-clasp bjam tool as directed in https://github.com/drmeister/clasp/issues/23, we get the following:
```
bash-3.2$ make boost-build-debug
make[1]: Entering directory '/Volumes/Filius/externals-clasp'
echo LDFLAGS=    processed =
LDFLAGS= processed =
(cd boost; \
			/Volumes/Filius/local/externals-clasp/release/bin/bjam toolset=gcc  \
			  \
			--with-filesystem --with-date_time	\
			--with-serialization --with-iostreams	\
			--with-program_options --with-regex	\
			--with-system --with-mpi\
			include=../zlib-1.2.8 linkflags=-L../zlib-1.2.8\
			--prefix=/Volumes/Filius/local/externals-clasp/debug \
			debug link=static \
			-j4 install --ignore-site-config )
config-cache.jam: No such file or directory
/Volumes/Filius/externals-clasp/boost/tools/build/v2/build-system.jam:696: in load
ERROR: rule "config-cache.load" unknown in module "build-system".
/Volumes/Filius/externals-clasp/boost/tools/build/v2/kernel/modules.jam:289: in import
/Volumes/Filius/externals-clasp/boost/tools/build/v2/kernel/bootstrap.jam:139: in boost-build
/Volumes/Filius/externals-clasp/boost/boost-build.jam:17: in module scope
makefile:311: recipe for target 'boost-build-debug' failed
make[1]: *** [boost-build-debug] Error 1
make[1]: Leaving directory '/Volumes/Filius/externals-clasp'
```
Note that by the time 'make' falls over, the release part if the build has completed its run and built both clang and clang++ --- using the same shell.
```
╭─chris@fergus /Volumes/Filius/local/externals-clasp/release/bin
╰─➤  ls
FileCheck           clang-format        llvm-bcanalyzer     llvm-mc             llvm-size           opt
b2                  clang-tblgen        llvm-config         llvm-mcmarkup       llvm-stress         verify-uselistorder
bjam                count               llvm-cov            llvm-nm             llvm-symbolizer     yaml2obj
bugpoint            llc                 llvm-diff           llvm-objdump        llvm-tblgen
c-index-test        lli                 llvm-dis            llvm-profdata       llvm-vtabledump
clang               lli-child-target    llvm-dwarfdump      llvm-ranlib         macho-dump
clang++             llvm-ar             llvm-extract        llvm-readobj        not
clang-check         llvm-as             llvm-link           llvm-rtdyld         obj2yaml

```
Which is why I'm surprised to see the debug side fall over. 

Using Macports gcc version 4.8 as detailed below:
```
bash-3.2$ gcc --version
gcc (MacPorts gcc48 4.8.3_3+universal) 4.8.3
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

bash-3.2$ which gcc
/opt/local/bin/gcc
```

**Comment by chriskmanx** [comment] 2015-01-22 21:34
This is OSX 10.9.4

**Comment by chriskmanx** [comment] 2015-01-22 21:36
This is reproducible by just typing make. It's a long build process with the release being first, and debug second, so the thinking behind typing "make boost-build-debug" is to short-circuit that long process and arriving at the error message quicker.

**Comment by Shinmera** [comment] 2015-09-25 21:29
This should be fixed in tandem with #134

**Comment by Shinmera** [comment] 2015-11-11 12:54
Unable to reproduce in recent builds. Closing for now.

**Closed by Shinmera** 2015-11-11 12:54 UTC
Labels: building
